# environment settings
seed: 0
precision: bf16
strategy: ddp
n_gpus: 2

# data arguments
dataset: datasets
test_split: muleshoe
num_workers: 4
shot: 30
eval_batch_size: 8
n_eval_batches: 40
img_size: 224
support_idx: 0
channel_idx: -1

# model arguments
model: UniAP
semseg_threshold: 0.2

# logging arguments
log_dir: TEST
save_dir: FINETUNE
load_dir: TRAIN
load_step: 0