# environment settings
seed: 0
precision: bf16
strategy: ddp
n_gpus: 1

# data arguments
dataset: UniASET
task_fold: 0
num_workers: 4
global_batch_size: 32
max_channels: 1
shot: 1
n_s: -1
domains_per_batch: 2
eval_batch_size: 8
n_eval_batches: 80
img_size: 224
image_augmentation: True
unary_augmentation: True
binary_augmentation: True
mixed_augmentation: True
channel_idx: -1

# model arguments
model: UniAP
image_backbone: beit_base_patch16_224_in22k
label_backbone: vit_base_patch16_224
image_encoder_weights: imagenet
drop_rate: 0.
drop_path_rate: 0.1
attn_drop_rate: 0.
n_attn_heads: 4
semseg_threshold: 0.2
channel_idx: -1
n_levels: 4
bitfit: True

# training arguments
n_steps: 200000
optimizer: adam
lr: 0.0001
lr_pretrained: 0.00001
lr_schedule: poly
lr_warmup: 1000
lr_warmup_scale: 0.
schedule_from: 0
weight_decay: 0.
lr_decay_degree: 0.9
mask_value: -1.
early_stopping_patience: -1
no_eval: True
continue_mode: False

# logging arguments
log_dir: TRAIN
save_dir: TRAIN
load_dir: TRAIN
log_iter: 100
val_iter: 20000
save_iter: 20000
load_step: -1